import pandas as pd
import numpy as np

from protein_visualizer.sample_data import PDB_TEXT
from protein_visualizer.services.conservation import parse_conservation_evidence_table
from protein_visualizer.services.literature_sites import fetch_literature_residue_evidence_for_structure
from protein_visualizer.services.parsers import parse_pdb_atoms
from protein_visualizer.services.pocket import (
    _build_consensus_pocket_table,
    _build_precision_residue_table,
    _infer_adaptive_detection_profile,
    _infer_structure_confidence_signal,
    _refine_kvfinder_residues,
    build_auto_pocket_display_table,
    build_pocket_detection_diagnostics_table,
    build_pocket_summary,
    detect_auto_pocket_table,
    get_pocket_detection_metadata,
    summarize_pocket_detection_metadata,
)


def test_detect_auto_pocket_table_generates_candidates_from_structure():
    pocket_df = detect_auto_pocket_table(PDB_TEXT)

    assert not pocket_df.empty
    assert {"pocket_id", "chain", "resid", "resname", "volume", "score"}.issubset(pocket_df.columns)
    assert {"detection_method", "detection_route", "depth_avg", "depth_max", "overlap_ratio", "proximity_distance", "precision_score", "seed_support", "confidence_score", "consensus_score", "consensus_methods", "method_vote_count", "consensus_overlap_ratio"}.issubset(pocket_df.columns)
    assert pocket_df["detection_method"].notna().all()
    assert pocket_df["detection_method"].astype(str).str.len().gt(0).all()
    assert pocket_df["detection_route"].notna().all()
    assert pocket_df["detection_route"].astype(str).str.len().gt(0).all()
    assert pocket_df["detection_route"].astype(str).str.startswith("precision-").all()
    assert pocket_df["method_vote_count"].astype(int).ge(1).all()

    summary = build_pocket_summary(pocket_df, pd.DataFrame())
    assert not summary.empty
    assert summary.iloc[0]["residue_count"] >= 1
    assert "detection_route" in summary.columns
    assert "consensus_methods" in summary.columns


def test_detect_auto_pocket_table_supports_fixed_and_adaptive_profiles():
    adaptive_df = detect_auto_pocket_table(PDB_TEXT)
    fixed_df = detect_auto_pocket_table(PDB_TEXT, adaptive_profile=False)

    assert not adaptive_df.empty
    assert not fixed_df.empty
    assert adaptive_df["detection_route"].astype(str).str.startswith("precision-").all()
    assert fixed_df["detection_route"].astype(str).str.startswith("precision-").all()


def test_infer_structure_confidence_signal_detects_predicted_models():
    b_factors = pd.Series([42.0, 68.0, 91.0])
    confidence_score, confidence_weight, confidence_mode = _infer_structure_confidence_signal(
        "REMARK Generated by AlphaFold with pLDDT scores",
        b_factors,
    )

    assert confidence_mode == "predicted-model"
    assert confidence_weight == 1.0
    assert float(confidence_score.iloc[-1]) > float(confidence_score.iloc[0])


def test_infer_adaptive_detection_profile_generates_multiscale_kvfinder_profiles():
    atom_df = parse_pdb_atoms(PDB_TEXT)
    residue_df, ligand_atoms = _build_precision_residue_table(
        atom_df,
        set(),
        pdb_text=PDB_TEXT,
        contact_cutoff=7.2,
        ligand_radius=4.5,
    )
    profile = _infer_adaptive_detection_profile(
        residue_df,
        ligand_atoms,
        hotspot_set=set(),
        contact_cutoff=7.2,
        cluster_cutoff=7.5,
        ligand_radius=4.5,
        top_fraction=0.25,
        min_candidates=2,
        max_candidates=12,
        max_pockets=4,
        kv_step=0.5,
        kv_probe_in=1.4,
        kv_probe_out=4.0,
        kv_volume_cutoff=5.0,
    )

    assert 5.8 <= float(profile["contact_cutoff"]) <= 8.8
    assert float(profile["cluster_cutoff"]) >= float(profile["contact_cutoff"])
    assert 0.16 <= float(profile["top_fraction"]) <= 0.32
    assert len(profile["kv_probe_profiles"]) >= 2


def test_build_auto_pocket_display_table_marks_selected_pocket_and_hotspots():
    pocket_df = detect_auto_pocket_table(PDB_TEXT)
    selected_pocket = pocket_df.iloc[0]["pocket_id"]
    selected_rows = pocket_df[pocket_df["pocket_id"] == selected_pocket]
    pocket_residues = [(row.chain, int(row.resid)) for row in selected_rows.itertuples(index=False)]

    display_df = build_auto_pocket_display_table(
        pocket_df[["chain", "resid", "resname"]].drop_duplicates(),
        pocket_residues,
        hotspot_residues=[(selected_rows.iloc[0]["chain"], int(selected_rows.iloc[0]["resid"]))],
        pocket_id=selected_pocket,
    )

    assert not display_df.empty
    assert {"display_color", "classification_label", "is_pocket", "is_hotspot"}.issubset(display_df.columns)
    assert display_df["is_pocket"].any()
    assert display_df["is_hotspot"].any()


def test_build_auto_pocket_display_table_can_limit_hotspots_to_selected_pocket():
    atom_df = pd.DataFrame(
        [
            {"chain": "A", "resid": 1, "resname": "ALA"},
            {"chain": "A", "resid": 2, "resname": "GLY"},
            {"chain": "A", "resid": 3, "resname": "SER"},
        ]
    )

    display_df = build_auto_pocket_display_table(
        atom_df,
        pocket_residues=[("A", 1), ("A", 2)],
        hotspot_residues=[("A", 1), ("A", 3)],
        pocket_id="AutoPocket-1",
        limit_hotspots_to_pocket=True,
    )

    hotspot_map = {
        (str(row.chain), int(row.resid)): bool(row.is_hotspot)
        for row in display_df.itertuples(index=False)
    }

    assert hotspot_map[("A", 1)] is True
    assert hotspot_map[("A", 2)] is False
    assert hotspot_map[("A", 3)] is False


def test_build_auto_pocket_display_table_uses_core_shell_rim_layers():
    atom_df = pd.DataFrame(
        [
            {"chain": "A", "resid": 1, "resname": "ALA"},
            {"chain": "A", "resid": 2, "resname": "GLY"},
            {"chain": "A", "resid": 3, "resname": "SER"},
            {"chain": "A", "resid": 4, "resname": "TYR"},
        ]
    )
    layered_rows = pd.DataFrame(
        [
            {"chain": "A", "resid": 1, "pocket_layer": "core"},
            {"chain": "A", "resid": 2, "pocket_layer": "shell"},
            {"chain": "A", "resid": 3, "pocket_layer": "rim"},
        ]
    )

    display_df = build_auto_pocket_display_table(
        atom_df,
        pocket_residues=[("A", 1), ("A", 2), ("A", 3)],
        hotspot_residues=[("A", 1)],
        pocket_id="AutoPocket-1",
        pocket_residue_layers=layered_rows,
    )

    layer_by_resid = {
        int(row.resid): str(row.pocket_layer)
        for row in display_df.itertuples(index=False)
    }
    color_by_resid = {
        int(row.resid): str(row.display_color)
        for row in display_df.itertuples(index=False)
    }
    label_by_resid = {
        int(row.resid): str(row.classification_label)
        for row in display_df.itertuples(index=False)
    }

    assert layer_by_resid[1] == "core"
    assert layer_by_resid[2] == "shell"
    assert layer_by_resid[3] == "rim"
    assert layer_by_resid[4] == ""
    assert color_by_resid[1] == "#991b1b"
    assert color_by_resid[2] == "#2563eb"
    assert color_by_resid[3] == "#14b8a6"
    assert "core" in label_by_resid[1]


def test_build_auto_pocket_display_table_scoped_hotspots_empty_without_selected_pocket():
    atom_df = pd.DataFrame(
        [
            {"chain": "A", "resid": 1, "resname": "ALA"},
            {"chain": "A", "resid": 2, "resname": "GLY"},
            {"chain": "A", "resid": 3, "resname": "SER"},
        ]
    )

    display_df = build_auto_pocket_display_table(
        atom_df,
        pocket_residues=[],
        hotspot_residues=[("A", 1), ("A", 3)],
        pocket_id=None,
        limit_hotspots_to_pocket=True,
    )

    assert not display_df["is_hotspot"].astype(bool).any()


def test_detect_auto_pocket_table_falls_back_to_heuristic_when_library_disabled():
    pocket_df = detect_auto_pocket_table(PDB_TEXT, prefer_kvfinder=False)

    assert not pocket_df.empty
    assert {"detection_method", "detection_route", "depth_avg", "depth_max", "overlap_ratio", "proximity_distance", "precision_score", "seed_support", "confidence_score", "consensus_score", "consensus_methods", "method_vote_count", "consensus_overlap_ratio"}.issubset(pocket_df.columns)
    assert pocket_df["detection_method"].isin(["ligand-proximity", "geometry-cluster"]).any()
    assert pocket_df["detection_route"].astype(str).str.startswith("precision-").all()


def test_detect_auto_pocket_table_uses_hotspot_guidance_when_seeded():
    pocket_df = detect_auto_pocket_table(PDB_TEXT, prefer_kvfinder=False, hotspot_residues=[("A", 1), ("A", 2)])

    assert not pocket_df.empty
    assert pocket_df["is_hotspot"].any()
    assert pocket_df["seed_support"].astype(float).gt(0).any()
    assert pocket_df["consensus_score"].astype(float).ge(0).all()


def test_detect_auto_pocket_table_keeps_hotspot_supported_residues_during_truncation():
    pocket_df = detect_auto_pocket_table(PDB_TEXT, prefer_kvfinder=False, hotspot_residues=[("A", 1), ("A", 2)])

    residue_keys = {(row.chain, int(row.resid)) for row in pocket_df.itertuples(index=False)}

    assert ("A", 1) in residue_keys
    assert ("A", 2) in residue_keys
    assert ("A", 4) not in residue_keys


def test_detect_auto_pocket_table_uses_external_site_evidence_during_detection():
    external_site_df = pd.DataFrame(
        [
            {
                "chain": "A",
                "resid": 1,
                "evidence_source": "M-CSA",
                "evidence_type": "Catalytic residue",
                "evidence_score": 1.0,
                "evidence_note": "Catalytic residue",
                "uniprot_resid": 1,
                "mapping_level": "exact",
                "mapping_confidence": 0.94,
                "mapping_method": "sifts-chain-map",
            }
        ]
    )

    pocket_df = detect_auto_pocket_table(
        PDB_TEXT,
        prefer_kvfinder=False,
        external_site_df=external_site_df,
    )

    assert not pocket_df.empty
    residue_view = pocket_df[(pocket_df["chain"].astype(str) == "A") & (pocket_df["resid"].astype(int) == 1)]
    assert not residue_view.empty
    assert residue_view["external_exact_match"].astype(bool).any()
    assert residue_view["external_support"].astype(float).gt(0.0).any()
    assert residue_view["seed_support"].astype(float).gt(0.0).any()
    assert residue_view["external_direct_anchor"].astype(bool).any()
    assert "M-CSA" in str(residue_view.iloc[0]["external_direct_sources"])
    assert "Catalytic residue" in str(residue_view.iloc[0]["external_evidence_types"])
    assert "Catalytic residue" in str(residue_view.iloc[0]["external_evidence_notes"])

    summary = build_pocket_summary(pocket_df, pd.DataFrame())
    assert "external_evidence_types" in summary.columns
    assert summary["external_evidence_types"].astype(str).str.contains("Catalytic residue").any()


def test_detect_auto_pocket_table_uses_literature_residue_evidence_during_detection():
    literature_df, literature_meta = fetch_literature_residue_evidence_for_structure(
        manual_text="The active site catalytic residue Ala1 is required for enzyme activity.",
        chain_hint="A",
        enable_pubmed=False,
        assume_structure_numbering=True,
    )

    pocket_df = detect_auto_pocket_table(
        PDB_TEXT,
        prefer_kvfinder=False,
        external_site_df=literature_df,
    )

    assert literature_meta["status"] == "ok"
    assert not pocket_df.empty
    residue_view = pocket_df[(pocket_df["chain"].astype(str) == "A") & (pocket_df["resid"].astype(int) == 1)]
    assert not residue_view.empty
    assert residue_view["external_exact_match"].astype(bool).any()
    assert residue_view["external_support"].astype(float).gt(0.0).any()
    assert residue_view["seed_support"].astype(float).gt(0.0).any()
    assert residue_view["external_direct_anchor"].astype(bool).any()
    assert "Literature" in str(residue_view.iloc[0]["external_direct_sources"])
    assert "Catalytic residue" in str(residue_view.iloc[0]["external_evidence_types"])


def test_detect_auto_pocket_table_adds_external_evidence_guided_route():
    external_site_df = pd.DataFrame(
        [
            {
                "chain": "A",
                "resid": 1,
                "evidence_source": "Literature+Structure",
                "evidence_type": "Catalytic residue",
                "evidence_score": 1.0,
                "evidence_note": "paper active site",
                "uniprot_resid": 1,
                "mapping_level": "exact",
                "mapping_confidence": 0.9,
                "mapping_method": "literature-structure-numbering",
            }
        ]
    )

    pocket_df = detect_auto_pocket_table(
        PDB_TEXT,
        prefer_kvfinder=False,
        prefer_ligand=False,
        external_site_df=external_site_df,
    )
    diagnostics = build_pocket_detection_diagnostics_table(pocket_df)

    assert not pocket_df.empty
    assert "external-evidence" in set(diagnostics["method"].astype(str))
    assert diagnostics.loc[diagnostics["method"].astype(str) == "external-evidence", "status"].iloc[0] == "used"
    assert pocket_df["consensus_methods"].astype(str).str.contains("external-evidence").any()
    summary = summarize_pocket_detection_metadata(get_pocket_detection_metadata(pocket_df))
    assert summary["auto_detection_external_route_status"] == "used"
    assert summary["auto_detection_external_route_min_support"] == 0.58
    residue_view = pocket_df[(pocket_df["chain"].astype(str) == "A") & (pocket_df["resid"].astype(int) == 1)]
    assert not residue_view.empty
    assert residue_view["detection_route"].astype(str).str.contains("external-evidence|consensus", regex=True).any()
    assert residue_view["external_direct_anchor"].astype(bool).any()
    assert residue_view["evidence_route_anchor"].astype(bool).any()
    assert pd.to_numeric(residue_view["evidence_anchor_distance"], errors="coerce").min() == 0.0
    assert "A:1" in str(residue_view.iloc[0]["evidence_anchor_residue"])
    pocket_summary = build_pocket_summary(pocket_df, pd.DataFrame())
    assert pocket_summary["external_direct_anchor_count"].astype(int).ge(1).any()
    assert pocket_summary["evidence_route_anchor_count"].astype(int).ge(1).any()
    assert "A:1" in str(pocket_summary.iloc[0]["evidence_anchor_residues"])


def test_detect_auto_pocket_table_can_disable_external_evidence_guided_route():
    external_site_df = pd.DataFrame(
        [
            {
                "chain": "A",
                "resid": 1,
                "evidence_source": "Literature+Structure",
                "evidence_type": "Catalytic residue",
                "evidence_score": 1.0,
                "evidence_note": "paper active site",
                "mapping_level": "exact",
                "mapping_confidence": 0.9,
                "mapping_method": "literature-structure-numbering",
            }
        ]
    )

    pocket_df = detect_auto_pocket_table(
        PDB_TEXT,
        prefer_kvfinder=False,
        prefer_ligand=False,
        external_site_df=external_site_df,
        enable_external_evidence_route=False,
    )
    diagnostics = build_pocket_detection_diagnostics_table(pocket_df)
    summary = summarize_pocket_detection_metadata(get_pocket_detection_metadata(pocket_df))

    assert "external-evidence" in set(diagnostics["method"].astype(str))
    assert diagnostics.loc[diagnostics["method"].astype(str) == "external-evidence", "status"].iloc[0] == "disabled"
    assert summary["auto_detection_external_route_enabled"] is False
    assert not pocket_df["detection_method"].astype(str).eq("external-evidence").any()
    assert not pocket_df["consensus_methods"].astype(str).str.contains("external-evidence", regex=False).any()


def test_detect_auto_pocket_table_rejects_weak_external_evidence_route_anchor():
    weak_external_site_df = pd.DataFrame(
        [
            {
                "chain": "A",
                "resid": 1,
                "evidence_source": "Literature",
                "evidence_type": "Possible activity residue",
                "evidence_score": 0.2,
                "evidence_note": "ambiguous weak mention",
                "mapping_level": "weak",
                "mapping_confidence": 0.2,
                "mapping_method": "low-confidence-literature-map",
            }
        ]
    )

    pocket_df = detect_auto_pocket_table(
        PDB_TEXT,
        prefer_kvfinder=False,
        prefer_ligand=False,
        external_site_df=weak_external_site_df,
    )
    diagnostics = build_pocket_detection_diagnostics_table(pocket_df)

    assert diagnostics.loc[diagnostics["method"].astype(str) == "external-evidence", "status"].iloc[0] == "empty"
    assert not pocket_df["detection_method"].astype(str).eq("external-evidence").any()
    assert not pocket_df["consensus_methods"].astype(str).str.contains("external-evidence", regex=False).any()
    residue_df, _ligand_atoms = _build_precision_residue_table(
        parse_pdb_atoms(PDB_TEXT),
        set(),
        pdb_text=PDB_TEXT,
        contact_cutoff=7.2,
        ligand_radius=4.5,
        external_site_df=weak_external_site_df,
    )
    weak_row = residue_df[(residue_df["chain"].astype(str) == "A") & (residue_df["resid"].astype(int) == 1)].iloc[0]
    assert bool(weak_row["external_direct_anchor"]) is False


def test_detect_auto_pocket_table_accepts_conservation_import_as_independent_signal():
    conservation_text = """chain,resid,grade,confidence
A,1,9,0.95
A,2,7,0.85
"""
    conservation_df, conservation_meta = parse_conservation_evidence_table(
        conservation_text,
        source_hint="ConSurf",
    )

    pocket_df = detect_auto_pocket_table(
        PDB_TEXT,
        prefer_kvfinder=False,
        hotspot_residues=[("A", 1)],
        conservation_site_df=conservation_df,
    )

    assert conservation_meta["status"] == "ok"
    assert not pocket_df.empty
    residue_view = pocket_df[(pocket_df["chain"].astype(str) == "A") & (pocket_df["resid"].astype(int) == 1)]
    summary = build_pocket_summary(pocket_df, pd.DataFrame())

    assert not residue_view.empty
    assert residue_view["conservation_support"].astype(float).gt(0.0).any()
    assert residue_view["external_support"].astype(float).eq(0.0).all()
    assert summary["conservation_support_mean"].astype(float).gt(0.0).any()
    assert "ConSurf" in str(summary.iloc[0]["conservation_sources"])


def test_precision_residue_table_prefers_structure_verified_external_alignment():
    atom_df = parse_pdb_atoms(PDB_TEXT)
    external_site_df = pd.DataFrame(
        [
            {
                "chain": "A",
                "resid": 1,
                "evidence_source": "UniProt+SIFTS",
                "evidence_type": "Active site",
                "evidence_score": 0.95,
                "mapping_level": "exact",
                "mapping_confidence": 0.96,
                "mapping_method": "sifts-structure-order",
            },
            {
                "chain": "A",
                "resid": 2,
                "evidence_source": "UniProt+SIFTS",
                "evidence_type": "Active site",
                "evidence_score": 0.95,
                "mapping_level": "weak",
                "mapping_confidence": 0.58,
                "mapping_method": "sifts-gap-fallback",
            },
        ]
    )

    residue_df, _ligand_atoms = _build_precision_residue_table(
        atom_df,
        set(),
        pdb_text=PDB_TEXT,
        contact_cutoff=7.2,
        ligand_radius=4.5,
        external_site_df=external_site_df,
    )

    verified_row = residue_df[(residue_df["chain"].astype(str) == "A") & (residue_df["resid"].astype(int) == 1)].iloc[0]
    fallback_row = residue_df[(residue_df["chain"].astype(str) == "A") & (residue_df["resid"].astype(int) == 2)].iloc[0]

    assert bool(verified_row["external_structure_verified"]) is True
    assert float(verified_row["external_mapping_quality"]) > float(fallback_row["external_mapping_quality"])
    assert float(verified_row["external_support"]) > float(fallback_row["external_support"])


def test_detect_auto_pocket_table_attaches_detection_metadata_and_diagnostics():
    external_site_df = pd.DataFrame(
        [
            {
                "chain": "A",
                "resid": 1,
                "evidence_source": "M-CSA",
                "evidence_type": "Catalytic residue",
                "evidence_score": 1.0,
                "mapping_level": "exact",
                "mapping_confidence": 0.94,
            }
        ]
    )

    pocket_df = detect_auto_pocket_table(
        PDB_TEXT,
        prefer_kvfinder=False,
        prefer_ligand=False,
        hotspot_residues=[("A", 1)],
        external_site_df=external_site_df,
    )

    metadata = get_pocket_detection_metadata(pocket_df)
    diagnostics_df = build_pocket_detection_diagnostics_table(pocket_df)
    summary = summarize_pocket_detection_metadata(metadata)

    assert metadata["result_pocket_count"] >= 1
    assert metadata["external_evidence"]["evidence_rows"] == 1
    assert not diagnostics_df.empty
    assert {"geometry-cluster", "consensus"}.issubset(set(diagnostics_df["method"].astype(str)))
    assert "geometry-cluster:used" in summary["auto_detection_status_summary"]
    assert summary["auto_detection_external_rows"] == 1
    assert summary["auto_detection_methods_used"]


def test_detect_auto_pocket_table_can_merge_p2rank_predictions_into_consensus(monkeypatch):
    pocket_predictions = pd.DataFrame(
        [
            {
                "pocket_label": "Pocket-1",
                "pocket_rank": 1,
                "pocket_score": 0.88,
                "pocket_probability": 0.91,
                "center_x": 0.0,
                "center_y": 0.0,
                "center_z": 0.0,
                "residue_list": "",
            }
        ]
    )
    residue_predictions = pd.DataFrame(
        [
            {"pocket_label": "Pocket-1", "pocket_rank": 1, "chain": "A", "resid": 1, "resname": "ALA", "residue_score": 0.90, "residue_probability": 0.94},
            {"pocket_label": "Pocket-1", "pocket_rank": 1, "chain": "A", "resid": 2, "resname": "TYR", "residue_score": 0.87, "residue_probability": 0.89},
        ]
    )

    monkeypatch.setattr(
        "protein_visualizer.services.pocket.run_p2rank",
        lambda *args, **kwargs: (pocket_predictions, residue_predictions, {"status": "ok"}),
    )

    pocket_df = detect_auto_pocket_table(
        PDB_TEXT,
        prefer_kvfinder=False,
        prefer_p2rank=True,
        prefer_ligand=False,
    )

    assert not pocket_df.empty
    assert pocket_df["consensus_methods"].astype(str).str.contains("p2rank").any()
    assert pocket_df["detection_route"].astype(str).str.contains("consensus|p2rank", regex=True).any()


def test_detection_metadata_summary_includes_p2rank_run_fields(monkeypatch):
    pocket_predictions = pd.DataFrame(
        [
            {
                "pocket_label": "Pocket-1",
                "pocket_rank": 1,
                "pocket_score": 0.88,
                "pocket_probability": 0.91,
                "center_x": 0.0,
                "center_y": 0.0,
                "center_z": 0.0,
                "residue_list": "",
            }
        ]
    )
    residue_predictions = pd.DataFrame(
        [
            {"pocket_label": "Pocket-1", "pocket_rank": 1, "chain": "A", "resid": 1, "resname": "ALA", "residue_score": 0.90, "residue_probability": 0.94},
        ]
    )

    monkeypatch.setattr(
        "protein_visualizer.services.pocket.run_p2rank",
        lambda *args, **kwargs: (
            pocket_predictions,
            residue_predictions,
            {
                "status": "ok",
                "return_code": 0,
                "prediction_rows": "1",
                "residue_rows": "1",
                "stdout": "done",
            },
        ),
    )

    pocket_df = detect_auto_pocket_table(
        PDB_TEXT,
        prefer_kvfinder=False,
        prefer_p2rank=True,
        prefer_ligand=False,
    )
    summary = summarize_pocket_detection_metadata(get_pocket_detection_metadata(pocket_df))

    assert summary["auto_detection_p2rank_status"] == "ok"
    assert summary["auto_detection_p2rank_prediction_rows"] == 1
    assert summary["auto_detection_p2rank_residue_rows"] == 1


def test_consensus_merge_prefers_multi_method_overlap():
    residue_df = pd.DataFrame(
        [
            {
                "chain": "A",
                "resid": 1,
                "resname": "ALA",
                "x": 0.0,
                "y": 0.0,
                "z": 0.0,
                "contact_count": 4,
                "center_distance": 1.0,
                "ligand_contact_count": 2,
                "is_hotspot": True,
                "seed_support": 0.9,
                "confidence_score": 0.8,
                "precision_score": 0.88,
            },
            {
                "chain": "A",
                "resid": 2,
                "resname": "TYR",
                "x": 1.0,
                "y": 0.2,
                "z": 0.0,
                "contact_count": 3,
                "center_distance": 1.2,
                "ligand_contact_count": 1,
                "is_hotspot": False,
                "seed_support": 0.7,
                "confidence_score": 0.75,
                "precision_score": 0.84,
            },
            {
                "chain": "A",
                "resid": 3,
                "resname": "GLU",
                "x": 0.4,
                "y": 1.0,
                "z": 0.0,
                "contact_count": 2,
                "center_distance": 1.4,
                "ligand_contact_count": 0,
                "is_hotspot": False,
                "seed_support": 0.5,
                "confidence_score": 0.7,
                "precision_score": 0.78,
            },
            {
                "chain": "A",
                "resid": 4,
                "resname": "LYS",
                "x": 9.0,
                "y": 0.0,
                "z": 0.0,
                "contact_count": 1,
                "center_distance": 4.5,
                "ligand_contact_count": 0,
                "is_hotspot": False,
                "seed_support": 0.2,
                "confidence_score": 0.55,
                "precision_score": 0.35,
            },
        ]
    )

    kvfinder_table = pd.DataFrame(
        [
            {"pocket_id": "KVFinder-1", "chain": "A", "resid": 1, "resname": "ALA", "volume": 120.0, "score": 0.91, "residue_score": 0.90, "contact_count": 4, "center_distance": 1.0, "ligand_contact_count": 2, "detection_method": "kvfinder-refined", "detection_route": "precision-kvfinder", "is_hotspot": True, "depth_avg": 1.1, "depth_max": 2.0, "overlap_ratio": 0.8, "proximity_distance": 0.6, "precision_score": 0.90, "seed_support": 0.92, "confidence_score": 0.81},
            {"pocket_id": "KVFinder-1", "chain": "A", "resid": 2, "resname": "TYR", "volume": 120.0, "score": 0.91, "residue_score": 0.87, "contact_count": 3, "center_distance": 1.2, "ligand_contact_count": 1, "detection_method": "kvfinder-refined", "detection_route": "precision-kvfinder", "is_hotspot": False, "depth_avg": 1.1, "depth_max": 2.0, "overlap_ratio": 0.8, "proximity_distance": 0.8, "precision_score": 0.87, "seed_support": 0.68, "confidence_score": 0.76},
            {"pocket_id": "KVFinder-1", "chain": "A", "resid": 3, "resname": "GLU", "volume": 120.0, "score": 0.91, "residue_score": 0.80, "contact_count": 2, "center_distance": 1.4, "ligand_contact_count": 0, "detection_method": "kvfinder-refined", "detection_route": "precision-kvfinder", "is_hotspot": False, "depth_avg": 1.1, "depth_max": 2.0, "overlap_ratio": 0.8, "proximity_distance": 1.1, "precision_score": 0.80, "seed_support": 0.52, "confidence_score": 0.71},
        ]
    )

    ligand_table = pd.DataFrame(
        [
            {"pocket_id": "Ligand-1", "chain": "A", "resid": 1, "resname": "ALA", "volume": 98.0, "score": 0.84, "residue_score": 0.83, "contact_count": 4, "center_distance": 1.0, "ligand_contact_count": 2, "detection_method": "ligand-proximity", "detection_route": "precision-ligand", "is_hotspot": True, "depth_avg": 0.9, "depth_max": 1.7, "overlap_ratio": 0.7, "proximity_distance": 0.5, "precision_score": 0.83, "seed_support": 0.90, "confidence_score": 0.82},
            {"pocket_id": "Ligand-1", "chain": "A", "resid": 2, "resname": "TYR", "volume": 98.0, "score": 0.84, "residue_score": 0.78, "contact_count": 3, "center_distance": 1.2, "ligand_contact_count": 1, "detection_method": "ligand-proximity", "detection_route": "precision-ligand", "is_hotspot": False, "depth_avg": 0.9, "depth_max": 1.7, "overlap_ratio": 0.7, "proximity_distance": 0.7, "precision_score": 0.78, "seed_support": 0.66, "confidence_score": 0.74},
            {"pocket_id": "Ligand-1", "chain": "A", "resid": 4, "resname": "LYS", "volume": 98.0, "score": 0.84, "residue_score": 0.35, "contact_count": 1, "center_distance": 4.5, "ligand_contact_count": 0, "detection_method": "ligand-proximity", "detection_route": "precision-ligand", "is_hotspot": False, "depth_avg": 0.9, "depth_max": 1.7, "overlap_ratio": 0.7, "proximity_distance": 4.2, "precision_score": 0.35, "seed_support": 0.22, "confidence_score": 0.57},
        ]
    )

    geometry_table = pd.DataFrame(
        [
            {"pocket_id": "Geometry-1", "chain": "A", "resid": 1, "resname": "ALA", "volume": 110.0, "score": 0.88, "residue_score": 0.86, "contact_count": 4, "center_distance": 1.0, "ligand_contact_count": 2, "detection_method": "geometry-cluster", "detection_route": "precision-geometry", "is_hotspot": True, "depth_avg": 1.0, "depth_max": 2.1, "overlap_ratio": 0.6, "proximity_distance": 0.7, "precision_score": 0.86, "seed_support": 0.88, "confidence_score": 0.80},
            {"pocket_id": "Geometry-1", "chain": "A", "resid": 2, "resname": "TYR", "volume": 110.0, "score": 0.88, "residue_score": 0.85, "contact_count": 3, "center_distance": 1.2, "ligand_contact_count": 1, "detection_method": "geometry-cluster", "detection_route": "precision-geometry", "is_hotspot": False, "depth_avg": 1.0, "depth_max": 2.1, "overlap_ratio": 0.6, "proximity_distance": 0.8, "precision_score": 0.85, "seed_support": 0.70, "confidence_score": 0.77},
            {"pocket_id": "Geometry-1", "chain": "A", "resid": 3, "resname": "GLU", "volume": 110.0, "score": 0.88, "residue_score": 0.82, "contact_count": 2, "center_distance": 1.4, "ligand_contact_count": 0, "detection_method": "geometry-cluster", "detection_route": "precision-geometry", "is_hotspot": False, "depth_avg": 1.0, "depth_max": 2.1, "overlap_ratio": 0.6, "proximity_distance": 1.2, "precision_score": 0.82, "seed_support": 0.55, "confidence_score": 0.72},
        ]
    )

    consensus_df = _build_consensus_pocket_table(
        [kvfinder_table, ligand_table, geometry_table],
        residue_df,
        hotspot_set={("A", 1)},
        cluster_cutoff=1.6,
        top_fraction=0.75,
        min_candidates=2,
        max_candidates=6,
        max_pockets=4,
    )

    assert not consensus_df.empty
    assert consensus_df["detection_route"].astype(str).str.contains("consensus").any()
    assert consensus_df["method_vote_count"].astype(int).ge(2).all()
    assert not consensus_df["resid"].astype(int).eq(4).any()
    assert consensus_df["consensus_methods"].astype(str).str.contains("+", regex=False).any()
    summary = build_pocket_summary(consensus_df, pd.DataFrame())
    assert "consensus_methods" in summary.columns
    assert "method_vote_count" in summary.columns


def test_refine_kvfinder_residues_prefers_supported_and_confident_residues():
    residues = [("A", 1, "ALA"), ("A", 2, "GLY"), ("A", 3, "SER")]
    residue_center_map = {
        ("A", 1): np.array([0.0, 0.0, 0.0]),
        ("A", 2): np.array([6.0, 0.0, 0.0]),
        ("A", 3): np.array([1.2, 0.2, 0.0]),
    }
    cavity_points = np.array(
        [
            [0.0, 0.0, 0.0],
            [0.2, 0.1, 0.0],
            [1.0, 0.0, 0.0],
            [1.1, 0.1, 0.0],
        ]
    )
    support_score_map = {("A", 1): 0.95, ("A", 2): 0.05, ("A", 3): 0.82}
    confidence_score_map = {("A", 1): 0.90, ("A", 2): 0.15, ("A", 3): 0.78}

    refined_residues, distance_map, cutoff, precision_map = _refine_kvfinder_residues(
        residues,
        residue_center_map,
        cavity_points,
        depth_avg=1.6,
        hotspot_set={("A", 1)},
        support_score_map=support_score_map,
        confidence_score_map=confidence_score_map,
    )

    assert cutoff is not None
    assert distance_map[("A", 1)] < distance_map[("A", 2)]
    assert ("A", 2, "GLY") not in refined_residues
    assert precision_map[("A", 1)] > precision_map[("A", 2)]
